/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login With Telegram */
        post: operations["login_with_telegram_api_v1_auth_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Balance */
        get: operations["get_balance_api_v1_balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_v1_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/expense": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Expense */
        post: operations["create_expense_api_v1_transactions_expense_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/income": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Income */
        post: operations["create_income_api_v1_transactions_income_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Transaction */
        delete: operations["delete_transaction_api_v1_transactions__transaction_id__delete"];
        options?: never;
        head?: never;
        /** Update Transaction */
        patch: operations["update_transaction_api_v1_transactions__transaction_id__patch"];
        trace?: never;
    };
    "/api/v1/currency/usd-rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usd Rate */
        get: operations["usd_rate_api_v1_currency_usd_rate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description Flat list (roots and children); `type=expense` also returns `both` categories.
         */
        get: operations["list_categories_api_v1_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_v1_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_api_v1_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Update Category */
        patch: operations["update_category_api_v1_categories__category_id__patch"];
        trace?: never;
    };
    "/api/v1/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Budgets */
        get: operations["list_budgets_api_v1_budgets_get"];
        /** Set Budget */
        put: operations["set_budget_api_v1_budgets_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/budgets/{budget_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Budget */
        delete: operations["delete_budget_api_v1_budgets__budget_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report */
        get: operations["report_api_v1_analytics_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/months": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Months */
        get: operations["months_api_v1_analytics_months_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/debts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Debts */
        get: operations["list_debts_api_v1_debts_get"];
        put?: never;
        /** Create Debt */
        post: operations["create_debt_api_v1_debts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/debts/{debt_id}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Settle Debt */
        post: operations["settle_debt_api_v1_debts__debt_id__settle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/debts/{debt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Debt */
        delete: operations["delete_debt_api_v1_debts__debt_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/savings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goals */
        get: operations["list_goals_api_v1_savings_get"];
        put?: never;
        /** Create Goal */
        post: operations["create_goal_api_v1_savings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/savings/{goal_id}/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deposit */
        post: operations["deposit_api_v1_savings__goal_id__deposit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reminders
         * @description Soonest payment first. Schedules are only included by the detail endpoint.
         */
        get: operations["list_reminders_api_v1_reminders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/credit/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Credit */
        post: operations["preview_credit_api_v1_reminders_credit_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/credit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Credit */
        post: operations["create_credit_api_v1_reminders_credit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/installment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Installment */
        post: operations["create_installment_api_v1_reminders_installment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/education": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Education */
        post: operations["create_education_api_v1_reminders_education_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/regular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Regular */
        post: operations["create_regular_api_v1_reminders_regular_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/{reminder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reminder */
        get: operations["get_reminder_api_v1_reminders__reminder_id__get"];
        put?: never;
        post?: never;
        /** Delete Reminder */
        delete: operations["delete_reminder_api_v1_reminders__reminder_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/{reminder_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Payment
         * @description Marks the current instalment as paid and moves to the next month.
         *     Does not create an expense transaction (same as the bot).
         */
        post: operations["record_payment_api_v1_reminders__reminder_id__payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Transactions */
        get: operations["export_transactions_api_v1_export_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountType
         * @enum {string}
         */
        AccountType: "cash" | "card" | "currency";
        /** BalanceResponse */
        BalanceResponse: {
            /** Cash Balance */
            cash_balance: string;
            /** Card Balance */
            card_balance: string;
            /** Currency Balance */
            currency_balance: string;
            /** Total Balance */
            total_balance: string;
            /** Total Income */
            total_income: string;
            /** Total Expense */
            total_expense: string;
            /** Total Savings */
            total_savings: string;
        };
        /** BudgetAlertResponse */
        BudgetAlertResponse: {
            /** Budget Id */
            budget_id: number;
            /** Category Name */
            category_name: string | null;
            /** Used Ratio */
            used_ratio: number;
            /** Limit */
            limit: string;
            /** Is Warning */
            is_warning: boolean;
            /** Is Critical */
            is_critical: boolean;
        };
        /**
         * BudgetPeriod
         * @enum {string}
         */
        BudgetPeriod: "daily" | "weekly" | "monthly";
        /** BudgetProgressResponse */
        BudgetProgressResponse: {
            /** Id */
            id: number;
            /** Category Id */
            category_id: number | null;
            /** Category Name */
            category_name: string | null;
            period: components["schemas"]["BudgetPeriod"];
            /** Limit Amount */
            limit_amount: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Spent */
            spent: string;
            /** Used Ratio */
            used_ratio: number;
            /** Is Warning */
            is_warning: boolean;
            /** Is Critical */
            is_critical: boolean;
        };
        /** BudgetResponse */
        BudgetResponse: {
            /** Id */
            id: number;
            /** Category Id */
            category_id: number | null;
            /** Category Name */
            category_name: string | null;
            period: components["schemas"]["BudgetPeriod"];
            /** Limit Amount */
            limit_amount: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
        };
        /** CategoryBreakdownResponse */
        CategoryBreakdownResponse: {
            /** Category Id */
            category_id: number;
            /** Category Name */
            category_name: string;
            /** Amount */
            amount: string;
            /** Percent */
            percent: number;
        };
        /** CategoryResponse */
        CategoryResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Icon */
            icon: string | null;
            /** Parent Id */
            parent_id: number | null;
            /** Is System */
            is_system: boolean;
            /**
             * Category Type
             * @enum {string}
             */
            category_type: "income" | "expense" | "both";
        };
        /** CreateCategoryRequest */
        CreateCategoryRequest: {
            /** Name */
            name: string;
            /** Icon */
            icon?: string | null;
            /** Parent Id */
            parent_id?: number | null;
            /**
             * Category Type
             * @default expense
             * @enum {string}
             */
            category_type: "income" | "expense" | "both";
        };
        /** CreateCreditRequest */
        CreateCreditRequest: {
            /**
             * First Payment Date
             * Format: date
             */
            first_payment_date: string;
            /** Name */
            name: string;
            /** Total Amount */
            total_amount: number | string;
            /** Interest Rate */
            interest_rate: number | string;
            /** Months Total */
            months_total: number;
            payment_type: components["schemas"]["PaymentType"];
        };
        /** CreateDebtRequest */
        CreateDebtRequest: {
            /** Counterparty */
            counterparty: string;
            /** Amount */
            amount: number | string;
            debt_type: components["schemas"]["DebtType"];
            /** Description */
            description?: string | null;
            /** Due Date */
            due_date?: string | null;
        };
        /** CreateEducationRequest */
        CreateEducationRequest: {
            /**
             * First Payment Date
             * Format: date
             */
            first_payment_date: string;
            /** Name */
            name: string;
            /** Total Amount */
            total_amount: number | string;
            /** Payment Amount */
            payment_amount: number | string;
        };
        /** CreateInstallmentRequest */
        CreateInstallmentRequest: {
            /**
             * First Payment Date
             * Format: date
             */
            first_payment_date: string;
            /** Name */
            name: string;
            /** Total Amount */
            total_amount: number | string;
            /** Monthly Payment */
            monthly_payment: number | string;
            /** Months Total */
            months_total: number;
        };
        /** CreateRegularRequest */
        CreateRegularRequest: {
            /**
             * First Payment Date
             * Format: date
             */
            first_payment_date: string;
            /** Name */
            name: string;
            /** Payment Amount */
            payment_amount: number | string;
        };
        /** CreateSavingsGoalRequest */
        CreateSavingsGoalRequest: {
            /** Name */
            name: string;
            /** Target Amount */
            target_amount: number | string;
            /** Description */
            description?: string | null;
            /** Deadline */
            deadline?: string | null;
        };
        /**
         * CreateTransactionRequest
         * @description `amount` is what the user typed, in `currency` (dollars for USD).
         *     The server converts USD to UZS with the current CBU rate.
         */
        CreateTransactionRequest: {
            /** Amount */
            amount: number | string;
            /**
             * Currency
             * @default UZS
             * @enum {string}
             */
            currency: "UZS" | "USD" | "CASH";
            /** Category Id */
            category_id?: number | null;
            /** Note */
            note?: string | null;
        };
        /** CreditPreviewRequest */
        CreditPreviewRequest: {
            /** Total Amount */
            total_amount: number | string;
            /** Interest Rate */
            interest_rate: number | string;
            /** Months Total */
            months_total: number;
            payment_type: components["schemas"]["PaymentType"];
        };
        /** CreditPreviewResponse */
        CreditPreviewResponse: {
            /** First Payment */
            first_payment: string;
            /** Total Payment */
            total_payment: string;
            /** Overpayment */
            overpayment: string;
            /** Schedule */
            schedule: components["schemas"]["ScheduleRowResponse"][];
        };
        /** DebtResponse */
        DebtResponse: {
            /** Id */
            id: number;
            /** Counterparty */
            counterparty: string;
            /** Amount */
            amount: string;
            debt_type: components["schemas"]["DebtType"];
            status: components["schemas"]["DebtStatus"];
            /** Description */
            description: string | null;
            /** Due Date */
            due_date: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DebtStatus
         * @enum {string}
         */
        DebtStatus: "active" | "settled" | "overdue";
        /**
         * DebtType
         * @enum {string}
         */
        DebtType: "i_owe" | "owed_to_me";
        /**
         * DepositRequest
         * @description Moves money from the card account into the goal (recorded as a savings transaction).
         */
        DepositRequest: {
            /** Amount */
            amount: number | string;
        };
        /** ExpenseCreatedResponse */
        ExpenseCreatedResponse: {
            transaction: components["schemas"]["TransactionResponse"];
            /** Alerts */
            alerts: components["schemas"]["BudgetAlertResponse"][];
        };
        /**
         * ExportFormat
         * @enum {string}
         */
        ExportFormat: "csv" | "xlsx";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: number;
            /** Timezone */
            timezone: string;
            balance: components["schemas"]["BalanceResponse"];
        };
        /** MonthResponse */
        MonthResponse: {
            /** Year */
            year: number;
            /** Month */
            month: number;
        };
        /**
         * PaymentType
         * @enum {string}
         */
        PaymentType: "annuity" | "differential";
        /**
         * RecordPaymentRequest
         * @description Omit `amount` to record the scheduled payment.
         */
        RecordPaymentRequest: {
            /** Amount */
            amount?: number | string | null;
        };
        /** ReminderResponse */
        ReminderResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            reminder_type: components["schemas"]["ReminderType"];
            status: components["schemas"]["ReminderStatus"];
            /** Payment Amount */
            payment_amount: string;
            /**
             * Next Payment Date
             * Format: date
             */
            next_payment_date: string;
            /** Total Amount */
            total_amount: string | null;
            /** Paid Amount */
            paid_amount: string;
            /** Remaining Amount */
            remaining_amount: string | null;
            /** Progress Percent */
            progress_percent: number | null;
            /** Months Paid */
            months_paid: number;
            /** Months Total */
            months_total: number | null;
            /** Interest Rate */
            interest_rate: string | null;
            payment_type: components["schemas"]["PaymentType"] | null;
            /** Payment Schedule */
            payment_schedule: components["schemas"]["ScheduleRowResponse"][] | null;
        };
        /**
         * ReminderStatus
         * @enum {string}
         */
        ReminderStatus: "active" | "completed";
        /**
         * ReminderType
         * @enum {string}
         */
        ReminderType: "credit" | "installment" | "education" | "regular";
        /**
         * ReportPeriod
         * @enum {string}
         */
        ReportPeriod: "day" | "week" | "month" | "year";
        /** ReportResponse */
        ReportResponse: {
            period: components["schemas"]["ReportPeriod"];
            /**
             * From Dt
             * Format: date-time
             */
            from_dt: string;
            /**
             * To Dt
             * Format: date-time
             */
            to_dt: string;
            /** Total Income */
            total_income: string;
            /** Total Expense */
            total_expense: string;
            /** Total Savings */
            total_savings: string;
            /** Balance */
            balance: string;
            /** Expense By Category */
            expense_by_category: components["schemas"]["CategoryBreakdownResponse"][];
            /** Income By Category */
            income_by_category: components["schemas"]["CategoryBreakdownResponse"][];
        };
        /** SavingsGoalResponse */
        SavingsGoalResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Target Amount */
            target_amount: string;
            /** Current Amount */
            current_amount: string;
            /** Remaining */
            remaining: string;
            /** Progress Percent */
            progress_percent: number;
            /** Description */
            description: string | null;
            /** Deadline */
            deadline: string | null;
            status: components["schemas"]["SavingsStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SavingsStatus
         * @enum {string}
         */
        SavingsStatus: "active" | "completed" | "cancelled";
        /** ScheduleRowResponse */
        ScheduleRowResponse: {
            /** Month */
            month: number;
            /** Payment */
            payment: string;
            /** Principal Part */
            principal_part: string;
            /** Interest Part */
            interest_part: string;
            /** Balance */
            balance: string;
        };
        /**
         * SetBudgetRequest
         * @description Upsert keyed by (category_id, period). `category_id: null` = overall budget.
         */
        SetBudgetRequest: {
            /** Category Id */
            category_id?: number | null;
            period: components["schemas"]["BudgetPeriod"];
            /** Limit Amount */
            limit_amount: number | string;
        };
        /** TelegramAuthRequest */
        TelegramAuthRequest: {
            /** Initdata */
            initData: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** TransactionListResponse */
        TransactionListResponse: {
            /** Items */
            items: components["schemas"]["TransactionResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** TransactionResponse */
        TransactionResponse: {
            /** Id */
            id: number;
            transaction_type: components["schemas"]["TransactionType"];
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            account_type: components["schemas"]["AccountType"];
            /** Original Amount */
            original_amount: string | null;
            /** Usd Rate */
            usd_rate: string | null;
            /** Category Id */
            category_id: number | null;
            /** Category Name */
            category_name: string | null;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TransactionType
         * @enum {string}
         */
        TransactionType: "income" | "expense" | "savings";
        /**
         * UpdateCategoryRequest
         * @description Send only what changes; `icon: null` removes the icon.
         */
        UpdateCategoryRequest: {
            /** Name */
            name?: string | null;
            /** Icon */
            icon?: string | null;
        };
        /** UpdateMeRequest */
        UpdateMeRequest: {
            /** Timezone */
            timezone: string;
        };
        /**
         * UpdateTransactionRequest
         * @description Partial update: send only what changes. `category_id: null` clears the category.
         *     `amount` is in the resulting currency (required when switching to USD).
         */
        UpdateTransactionRequest: {
            /** Amount */
            amount?: number | string | null;
            /** Currency */
            currency?: ("UZS" | "USD" | "CASH") | null;
            /** Category Id */
            category_id?: number | null;
            /** Note */
            note?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** UsdRateResponse */
        UsdRateResponse: {
            /** Rate */
            rate: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_with_telegram_api_v1_auth_telegram_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_balance_api_v1_balance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceResponse"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    update_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_v1_transactions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                type?: components["schemas"]["TransactionType"] | null;
                category_id?: number | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expense_api_v1_transactions_expense_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_income_api_v1_transactions_income_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_api_v1_transactions__transaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_api_v1_transactions__transaction_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTransactionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usd_rate_api_v1_currency_usd_rate_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsdRateResponse"];
                };
            };
        };
    };
    list_categories_api_v1_categories_get: {
        parameters: {
            query?: {
                type?: ("income" | "expense" | "both") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_api_v1_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_v1_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_v1_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_budgets_api_v1_budgets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetProgressResponse"][];
                };
            };
        };
    };
    set_budget_api_v1_budgets_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetBudgetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_budget_api_v1_budgets__budget_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_v1_analytics_report_get: {
        parameters: {
            query?: {
                period?: components["schemas"]["ReportPeriod"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    months_api_v1_analytics_months_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthResponse"][];
                };
            };
        };
    };
    list_debts_api_v1_debts_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["DebtStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_debt_api_v1_debts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDebtRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settle_debt_api_v1_debts__debt_id__settle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                debt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_debt_api_v1_debts__debt_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                debt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goals_api_v1_savings_get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoalResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_goal_api_v1_savings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSavingsGoalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deposit_api_v1_savings__goal_id__deposit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepositRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reminders_api_v1_reminders_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ReminderStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_credit_api_v1_reminders_credit_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_credit_api_v1_reminders_credit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCreditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_installment_api_v1_reminders_installment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInstallmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_education_api_v1_reminders_education_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEducationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_regular_api_v1_reminders_regular_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRegularRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reminder_api_v1_reminders__reminder_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminder_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_reminder_api_v1_reminders__reminder_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminder_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_payment_api_v1_reminders__reminder_id__payments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminder_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RecordPaymentRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_transactions_api_v1_export_transactions_get: {
        parameters: {
            query?: {
                format?: components["schemas"]["ExportFormat"];
                /** @description Any day in the target month; defaults to the current month */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
